
CREATE TABLE [dbo].[leapsAdmin]
(
[ADMIN_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ADMIN_NAME] VARCHAR(20) NULL, 
    [ADMIN_SURNAME] VARCHAR(20) NULL, 
    [ADMIN_EMAIL] VARCHAR(50) NULL, 
    [ADMIN_PASSWORD] VARCHAR(MAX) NULL, 
    [ADMIN_PHONE] VARCHAR(10) NULL, 
    [ADMIN_PHOTO] VARCHAR(MAX) NULL
)